import { StudySpec, BoundaryCondition, LoadSpec } from './spec';
import { STUDY_UNITS } from './units';

/** Format a number so integers read as floats (210000 -> "210000.0"). */
function num(n: number): string {
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
}

/** code_aster group list: ("A",) for one, ("A", "B") for many. */
function groupTuple(groups: string[]): string {
  return `(${groups.map((g) => `"${g}"`).join(', ')}${groups.length === 1 ? ',' : ''})`;
}

const SCENARIO_TITLE: Record<StudySpec['scenario'], string> = {
  'linear-static': 'Linear elastic static analysis',
  'nonlinear-static': 'Nonlinear static analysis',
  modal: 'Modal analysis',
};

const DOF_ORDER = ['DX', 'DY', 'DZ', 'DRX', 'DRY', 'DRZ'];

function header(spec: StudySpec): string {
  if (spec.comments === false) {
    return '';
  }
  return [
    '# Generated by VS Code Aster - https://github.com/simvia-tech/vs-code-aster',
    `# Scenario: ${SCENARIO_TITLE[spec.scenario]} (MODELISATION="${spec.modelization}")`,
    '',
  ].join('\n');
}

function meshBlock(): string {
  return `mesh = LIRE_MAILLAGE(FORMAT="MED", UNITE=${STUDY_UNITS.mesh})`;
}

function modelBlock(spec: StudySpec): string {
  return [
    'model = AFFE_MODELE(',
    '    MAILLAGE=mesh,',
    `    AFFE=_F(TOUT="OUI", PHENOMENE="MECANIQUE", MODELISATION="${spec.modelization}"),`,
    ')',
  ].join('\n');
}

function materialBlock(spec: StudySpec): string {
  const elas = [`E=${num(spec.material.young)}`, `NU=${num(spec.material.poisson)}`];
  if (spec.material.rho !== undefined) {
    elas.push(`RHO=${num(spec.material.rho)}`);
  }
  const factors = [`ELAS=_F(${elas.join(', ')})`];
  if (spec.scenario === 'nonlinear-static' && spec.material.yieldStress !== undefined) {
    const hardening = spec.material.hardening ?? spec.material.young / 100;
    factors.push(
      `ECRO_LINE=_F(SY=${num(spec.material.yieldStress)}, D_SIGM_EPSI=${num(hardening)})`
    );
  }
  if (factors.length === 1) {
    return `material = DEFI_MATERIAU(${factors[0]})`;
  }
  return ['material = DEFI_MATERIAU(', ...factors.map((f) => `    ${f},`), ')'].join('\n');
}

function materialFieldBlock(spec: StudySpec): string {
  const target =
    spec.materialGroups.length > 0 ? `GROUP_MA=${groupTuple(spec.materialGroups)}` : 'TOUT="OUI"';
  return [
    'material_field = AFFE_MATERIAU(',
    '    MAILLAGE=mesh,',
    `    AFFE=_F(${target}, MATER=material),`,
    ')',
  ].join('\n');
}

/** AFFE_CARA_ELEM block; empty string for continuum modelizations. */
function caraElemBlock(spec: StudySpec): string {
  const props = spec.structuralProps;
  if (!spec.isStructural || !props) {
    return '';
  }
  if (props.kind === 'shell') {
    return [
      'element_properties = AFFE_CARA_ELEM(',
      '    MODELE=model,',
      `    COQUE=_F(GROUP_MA=${groupTuple(props.groups)}, EPAIS=${num(props.thickness)}, VECTEUR=(0.0, 0.0, 1.0)),`,
      ')',
    ].join('\n');
  }
  // beam
  const sec = props.section;
  const cara =
    sec.type === 'CERCLE'
      ? { names: ['R'], values: [sec.R] }
      : { names: ['HY', 'HZ'], values: [sec.HY, sec.HZ] };
  return [
    'element_properties = AFFE_CARA_ELEM(',
    '    MODELE=model,',
    '    POUTRE=_F(',
    `        GROUP_MA=${groupTuple(props.groups)},`,
    `        SECTION="${sec.type}",`,
    `        CARA=${groupTuple(cara.names)},`,
    `        VALE=(${cara.values.map(num).join(', ')}${cara.values.length === 1 ? ',' : ''}),`,
    '    ),',
    ')',
  ].join('\n');
}

/** Whether the solver/assembly call should receive CARA_ELEM=element_properties. */
function caraElemArg(spec: StudySpec): string | null {
  return spec.isStructural && spec.structuralProps ? 'CARA_ELEM=element_properties' : null;
}

function dofString(bc: BoundaryCondition): string {
  return DOF_ORDER.filter((d) => d in bc.dofs)
    .map((d) => `${d}=${num(bc.dofs[d])}`)
    .join(', ');
}

function bcBlock(spec: StudySpec): string {
  const factors = spec.boundaryConditions.map((bc) => {
    const target = `${bc.groupKind}=${groupTuple(bc.groups)}`;
    return `    DDL_IMPO=_F(${target}, ${dofString(bc)}),`;
  });
  return ['boundary_condition = AFFE_CHAR_MECA(', '    MODELE=model,', ...factors, ')'].join('\n');
}

function loadFactor(load: LoadSpec): string {
  const target = `${load.groupKind}=${groupTuple(load.groups)}`;
  const comps = load.components ?? {};
  const compStr = (['FX', 'FY', 'FZ'] as const)
    .filter((c) => comps[c] !== undefined)
    .map((c) => `${c}=${num(comps[c] as number)}`)
    .join(', ');
  switch (load.type) {
    case 'PRES_REP':
      return `    PRES_REP=_F(${target}, PRES=${num(load.value ?? 0)}),`;
    case 'FORCE_FACE':
      return `    FORCE_FACE=_F(${target}, ${compStr}),`;
    case 'FORCE_ARETE':
      return `    FORCE_ARETE=_F(${target}, ${compStr}),`;
    case 'FORCE_NODALE':
      return `    FORCE_NODALE=_F(${target}, ${compStr}),`;
    case 'PESANTEUR': {
      const dir = `DIRECTION=(${num(comps.FX ?? 0)}, ${num(comps.FY ?? 0)}, ${num(comps.FZ ?? -1)})`;
      return `    PESANTEUR=_F(GRAVITE=${num(load.value ?? 9.81)}, ${dir}),`;
    }
  }
}

function loadBlock(spec: StudySpec): string {
  if (!spec.load) {
    return '';
  }
  return ['load = AFFE_CHAR_MECA(', '    MODELE=model,', loadFactor(spec.load), ')'].join('\n');
}

function calcChampBlock(): string {
  return [
    'result = CALC_CHAMP(',
    '    reuse=result,',
    '    RESULTAT=result,',
    '    CONTRAINTE=("SIGM_ELNO",),',
    '    CRITERES=("SIEQ_ELNO",),',
    ')',
  ].join('\n');
}

function imprResuBlock(resultName: string): string {
  return [
    'IMPR_RESU(',
    '    FORMAT="MED",',
    `    UNITE=${STUDY_UNITS.result},`,
    `    RESU=_F(RESULTAT=${resultName}),`,
    ')',
  ].join('\n');
}

function indentArg(arg: string): string {
  return `    ${arg},`;
}

function linearStatic(spec: StudySpec): string[] {
  const cara = caraElemArg(spec);
  const solver = [
    'result = MECA_STATIQUE(',
    '    MODELE=model,',
    '    CHAM_MATER=material_field,',
    ...(cara ? [indentArg(cara)] : []),
    '    EXCIT=(_F(CHARGE=boundary_condition), _F(CHARGE=load)),',
    ')',
  ].join('\n');
  return [solver, calcChampBlock(), imprResuBlock('result')];
}

function nonlinearStatic(spec: StudySpec): string[] {
  const cara = caraElemArg(spec);
  const relation = spec.material.yieldStress !== undefined ? 'VMIS_ISOT_LINE' : 'ELAS';
  const ramp = [
    'load_ramp = DEFI_FONCTION(',
    '    NOM_PARA="INST",',
    '    VALE=(0.0, 0.0, 1.0, 1.0),',
    '    PROL_DROITE="LINEAIRE",',
    '    PROL_GAUCHE="CONSTANT",',
    ')',
  ].join('\n');
  const timeList = [
    'time_list = DEFI_LIST_REEL(',
    '    DEBUT=0.0,',
    '    INTERVALLE=_F(JUSQU_A=1.0, NOMBRE=10),',
    ')',
  ].join('\n');
  const solver = [
    'result = STAT_NON_LINE(',
    '    MODELE=model,',
    '    CHAM_MATER=material_field,',
    ...(cara ? [indentArg(cara)] : []),
    '    EXCIT=(',
    '        _F(CHARGE=boundary_condition),',
    '        _F(CHARGE=load, FONC_MULT=load_ramp),',
    '    ),',
    `    COMPORTEMENT=_F(RELATION="${relation}", DEFORMATION="PETIT"),`,
    '    INCREMENT=_F(LIST_INST=time_list),',
    '    NEWTON=_F(REACTUALISATION="TANGENTE", MATRICE="TANGENTE"),',
    '    CONVERGENCE=_F(RESI_GLOB_RELA=1e-6, ITER_GLOB_MAXI=20),',
    ')',
  ].join('\n');
  return [ramp, timeList, solver, calcChampBlock(), imprResuBlock('result')];
}

function modal(spec: StudySpec): string[] {
  const cara = caraElemArg(spec);
  const caraLine = cara ? [`    ${cara},`] : [];
  const nmodes = spec.modal?.nmodes ?? 10;
  const rigidityElem = [
    'rigidity_elem = CALC_MATR_ELEM(',
    '    OPTION="RIGI_MECA",',
    '    MODELE=model,',
    '    CHAM_MATER=material_field,',
    ...caraLine,
    '    CHARGE=boundary_condition,',
    ')',
  ].join('\n');
  const massElem = [
    'mass_elem = CALC_MATR_ELEM(',
    '    OPTION="MASS_MECA",',
    '    MODELE=model,',
    '    CHAM_MATER=material_field,',
    ...caraLine,
    '    CHARGE=boundary_condition,',
    ')',
  ].join('\n');
  const dof = 'dof_numbering = NUME_DDL(MATR_RIGI=rigidity_elem)';
  const stiffness =
    'stiffness_matrix = ASSE_MATRICE(MATR_ELEM=rigidity_elem, NUME_DDL=dof_numbering)';
  const mass = 'mass_matrix = ASSE_MATRICE(MATR_ELEM=mass_elem, NUME_DDL=dof_numbering)';
  const calcModes = [
    'modes = CALC_MODES(',
    '    MATR_RIGI=stiffness_matrix,',
    '    MATR_MASS=mass_matrix,',
    '    OPTION="PLUS_PETITE",',
    `    CALC_FREQ=_F(NMAX_FREQ=${nmodes}),`,
    ')',
  ].join('\n');
  return [rigidityElem, massElem, dof, stiffness, mass, calcModes, imprResuBlock('modes')];
}

/**
 * Generates a complete, runnable .comm command file for the given study spec.
 * Pure: same spec in => same text out.
 */
export function generateComm(spec: StudySpec): string {
  const blocks: string[] = [];
  blocks.push('DEBUT(CODE=_F(NIV_PUB_WEB="INTERNET"), LANG="EN")');
  blocks.push(meshBlock());
  blocks.push(modelBlock(spec));
  blocks.push(materialBlock(spec));
  blocks.push(materialFieldBlock(spec));

  const cara = caraElemBlock(spec);
  if (cara) {
    blocks.push(cara);
  }

  blocks.push(bcBlock(spec));

  const load = loadBlock(spec);
  if (load) {
    blocks.push(load);
  }

  if (spec.scenario === 'linear-static') {
    blocks.push(...linearStatic(spec));
  } else if (spec.scenario === 'nonlinear-static') {
    blocks.push(...nonlinearStatic(spec));
  } else {
    blocks.push(...modal(spec));
  }

  blocks.push('FIN()');

  const head = header(spec);
  return (head ? head + '\n' : '') + blocks.join('\n\n') + '\n';
}
