import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { generateComm } from './generateComm';
import type { StudySpec } from './spec';

function spec(name: string): StudySpec {
  return JSON.parse(
    fs.readFileSync(path.join(__dirname, 'fixtures', name, 'spec.json'), 'utf8')
  ) as StudySpec;
}

describe('generateComm — scenario branches', () => {
  it('always wraps the study in DEBUT / FIN', () => {
    const c = generateComm(spec('linear-static-3d'));
    expect(c.trimStart().startsWith('# Generated by VS Code Aster')).toBe(true);
    expect(c).toContain('DEBUT(CODE=_F(NIV_PUB_WEB="INTERNET"), LANG="EN")');
    expect(c.trimEnd().endsWith('FIN()')).toBe(true);
    expect(c).toContain('LIRE_MAILLAGE(FORMAT="MED", UNITE=20)');
    expect(c).toContain('IMPR_RESU(');
  });

  it('linear-static 3D: MECA_STATIQUE, MODELISATION 3D, and NO CARA_ELEM', () => {
    const c = generateComm(spec('linear-static-3d'));
    expect(c).toContain('MECA_STATIQUE');
    expect(c).toContain('MODELISATION="3D"');
    expect(c).not.toContain('AFFE_CARA_ELEM');
    expect(c).not.toContain('CARA_ELEM=');
    // 3D solid BC must not impose rotational DOFs.
    expect(c).not.toContain('DRX=');
  });

  it('shell DKT: AFFE_CARA_ELEM defines element_properties wired via CARA_ELEM', () => {
    const c = generateComm(spec('shell-dkt'));
    expect(c).toContain('MODELISATION="DKT"');
    expect(c).toContain('element_properties = AFFE_CARA_ELEM(');
    expect(c).toContain('COQUE=_F(');
    expect(c).toContain('EPAIS=0.01');
    expect(c).toContain('CARA_ELEM=element_properties');
    // structural BC includes rotational DOFs
    expect(c).toContain('DRX=0.0');
  });

  it('beam POU_D_T: AFFE_CARA_ELEM POUTRE section wired via CARA_ELEM', () => {
    const c = generateComm(spec('beam-poutre'));
    expect(c).toContain('MODELISATION="POU_D_T"');
    expect(c).toContain('element_properties = AFFE_CARA_ELEM(');
    expect(c).toContain('POUTRE=_F(');
    expect(c).toContain('SECTION="RECTANGLE"');
    expect(c).toContain('CARA_ELEM=element_properties');
    expect(c).toContain('FORCE_NODALE=_F(GROUP_NO=("TIP",)');
  });

  it('nonlinear: STAT_NON_LINE skeleton, not MECA_STATIQUE', () => {
    const c = generateComm(spec('nonlinear-stat'));
    expect(c).toContain('STAT_NON_LINE');
    expect(c).not.toContain('MECA_STATIQUE');
    expect(c).toContain('load_ramp = DEFI_FONCTION(');
    expect(c).toContain('time_list = DEFI_LIST_REEL(');
    expect(c).toContain('COMPORTEMENT=_F(RELATION="VMIS_ISOT_LINE"');
    expect(c).toContain('CONVERGENCE=_F(');
    expect(c).toContain('ECRO_LINE=_F(SY=250.0');
  });

  it('modal: CALC_MODES from assembled stiffness/mass matrices, density required, no load', () => {
    const c = generateComm(spec('modal-modes'));
    expect(c).toContain('CALC_MODES');
    expect(c).toContain('rigidity_elem = CALC_MATR_ELEM(');
    expect(c).toContain('stiffness_matrix = ASSE_MATRICE(');
    expect(c).toContain('mass_matrix = ASSE_MATRICE(');
    expect(c).toContain('dof_numbering = NUME_DDL(');
    expect(c).toContain('RHO=7800.0');
    expect(c).not.toMatch(/^load = /m);
    expect(c).not.toContain('MECA_STATIQUE');
  });
});
